### ISSUE TITLE
Wrong Language Displayed When Using "Your Collection"

### ISSUE THREAD

**Issue by pmonofre** [raithos/xwing#1053] opened 2022-04-13 16:28 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** Make sure that this is a bug and not a misinterpretation of the rules! Lately we've gotten a lot of reports of things that are correct that are being listed as bugs.
**Note 2:** YASB.APP is the official version of the site now. raithos.github.io is no longer supported.

### Expected Behavior

When selecting "Your Collection", Expansions, Ships, Pilots, Upgrades, and Inventory should be in the chosen language (in my case, English).

### Actual Behavior

Expansions and Inventory are in English, but Ships, Pilots, and Upgrades are in French.

### Language

English

**Comment by raithos** [comment] 2022-04-18 12:26
I tried to reproduce this and could not. Could you provide a screenshot with the error, and what browser youre using?

**Comment by EarthaMajor** [comment] 2022-05-19 16:03
I'm getting this too. Brave browser - setting in app is English
![Screenshot 2022-05-19 120144](https://user-images.githubusercontent.com/20894834/169345948-350cc004-eb88-4d8a-95e1-b8f39d893e4d.jpg)

**Comment by raithos** [comment] 2022-05-19 19:11
I cant test this, but i pushed a fix for this. If its still happening ping here and I'll reopen

**Closed by raithos** 2022-05-19 19:11 UTC

**Comment by EarthaMajor** [comment] 2022-05-20 13:23
Seems to be working - thanks!

Derrick Beasley

------- Original Message -------

**Comment by pmonofre** [comment] 2022-10-11 08:30
Images below

[image: Screen Shot 2022-04-19 at 1.13.43 PM.png]

[image: Screen Shot 2022-04-19 at 1.13.26 PM.png]
[image: Screen Shot 2022-04-19 at 1.13.09 PM.png]
