### ISSUE TITLE
Alpha-class Star Wing "typo"

### ISSUE THREAD

**Issue by RobinZ94** [raithos/xwing#1421] opened 2024-09-10 18:30 UTC
Heavy Plasma Missiles is missing the target lock requirement and has a front full arc instead of the front arc. Also a typo "your" on Saturation Rockets.

absoluteley love your work <3

**Comment by Patschke** [comment] 2024-09-10 19:25
Thanks. Duplicate of #1417

**Closed** 2024-09-11 04:21 UTC
