### ISSUE TITLE
Cannot save obstacles after ships 

### ISSUE THREAD

**Issue by grim0126** [raithos/xwing#1272] opened 2023-05-11 19:04 UTC
**Describe the bug**
Obstacles do not save after ships have been chosen. Many times you are fiddling with ship lists before thinking or tweaking obstacles. it would be nice if obstacles saved after choosing ships. 

**To Reproduce**
Start a new squad. 
Pick ships
then attempt to pick obstacles and export the list somewhere

**Expected behavior**
I would like to be able to have the obstacles chosen after ships, have it stay with the list when copying the export link to Roll Better... or anywhere else. 

**Screenshots**
![image](https://github.com/raithos/xwing/assets/71295595/78aef08b-865a-49ab-8278-e1546d9821c6)

**Desktop (please complete the following information):**
![image](https://github.com/raithos/xwing/assets/71295595/6ef54bc2-8dfc-4ab8-b2d3-44be05ffb217)

**Comment by raithos** [comment] 2023-05-11 20:03
Not able to reproduce. when i make a list, i can select obstacles and save them just fine

**Comment by grim0126** [comment] 2023-05-11 20:31
are you doing that before or after ships have been selected?
Thanks!
Jason

**Comment by raithos** [comment] 2023-05-11 21:45
Both. What browser are you using and have you refreshed the page recently

**Comment by raithos** [comment] 2023-05-19 06:17
going to close this as im unable to reproduce it

**Closed by raithos** 2023-05-19 06:17 UTC
