### ISSUE TITLE
Wartime Loadout

### ISSUE THREAD

**Issue by Kleeg005** [raithos/xwing#874] opened 2021-10-06 23:06 UTC
### Expected Behavior

The "Wartime Loadout" Configuration for the Resistance Y-Wing is "Standardized" and should automatically propagate throughout a list to ensure list legality.

### Actual Behavior

I can currently build a list in which I have both the "Wartime Loadout" Configuration as well as standard, non-Configured ships.

### Language
English.

**Comment by Patschke** [comment] 2021-10-07 06:10
Duplicate of #873

**Closed** 2021-10-08 21:39 UTC
