### ISSUE TITLE
Epic quickbuild 

### ISSUE THREAD

**Issue by Gdsimms** [raithos/xwing#482] opened 2019-12-08 00:30 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** When switching between Epic and other formats, the Command upgrades stay on the ships, though no new upgrades are selectable. Please note that in your list building, I am aware and working on a fix for that issue.

### Expected Behavior

Drop down list of game modes, looking for “epic quickbuild “

### Actual Behavior

Not there. No huge ships or wings in quickbuild mode. 

### Language

The affected language(s).

**Comment by Patschke** [comment] 2019-12-08 00:31
Duplicate of #464 I guess? But thanks for the note.

**Comment by raithos** [comment] 2019-12-09 17:00
Im going to close this because yes, its a duplicate of #464

**Closed by raithos** 2019-12-09 17:00 UTC
