### ISSUE TITLE
 FO squads will not load?

### ISSUE THREAD

**Issue by BrunoIlic380** [raithos/xwing#521] opened 2020-01-23 18:20 UTC
### Expected Behavior

loading a first order squad

### Actual Behavior

when trying to load FO squads it just pinwheels "Fetching Squads"
all other factions' saved squads appear as normal

### Language

english

**Comment by sirjorj** [comment] 2020-01-23 20:03
Did you recently save a FO list?  I noticed this today when I saved a Separatist list and now Load Squad hangs for Separatist for me.  I then saved a new FO list and now FO does that too.  i think there is some corruption or something when it saves your squads.

**Comment by raithos** [comment] 2020-01-24 01:40
duplicate of #514

**Closed by raithos** 2020-01-24 01:40 UTC
