### ISSUE TITLE
Ex lists become Hyper when switching faction tabs

### ISSUE THREAD

**Issue by Neuvost** [raithos/xwing#604] opened 2020-07-30 20:02 UTC
## YASB 2.0 Bug Report
Hello! Thanks for everything you do! You're great! 
This is a small issue—far from a priority—but I figured I'd mention it. 
Windows 10.0.18362
Chrome Version 84.0.4147.105 (Official Build) (64-bit)

### Expected Behavior

When I switch faction tabs, Extended lists will remain the same (Extended) when I switch back to them.

### Actual Behavior

When I switch back to a faction tab, Extended lists are now Hyperspace, removing any cards not in Hyper. I must reload the Ex list to see it in whole.

### Language

English

Stay beautiful!

**Comment by Patschke** [comment] 2020-07-31 09:42
I can't reproduce this. If I choose Extended, add some ships, switch to another faction, and switch back, everything is still the same.

Did you change the format while beeing in the other factions tab? As the format is applied globally, this will change the other list as well. This behavior is intended, as usually one will rather look around different factions in the same format. 

If you can provide a step-by-step description of how to reproduce the behavior you described, I can try to fix it. As long as it does not occur for me, I can't ;-)

**Comment by Neuvost** [comment] 2020-07-31 20:29
Oh well. Thanks anyway. If I find a clearer pattern for reproduction I'll
letcha know. =)

**Comment by raithos** [comment] 2020-08-01 16:22
Closing this until we get more input

**Closed by raithos** 2020-08-01 16:22 UTC
