### ISSUE TITLE
Uncaught Type Error when loading a squad

### ISSUE THREAD

**Issue by AxisofeviI** [raithos/xwing#513] opened 2020-01-22 13:57 UTC
### Expected Behavior

Should load my list of squads for me to choose from. Happens with rebels only, yes I tried in incognito a few minutes later to confirm the issue.

### Actual Behavior

The page just hangs on the spinner that says "Fetching Squads". The console (in chrome) gives the following error:
![image](https://user-images.githubusercontent.com/36081629/72900012-22663880-3cf5-11ea-8c1b-4b32d825e9ed.png)

It was working fine just minutes before. The last thin I had done was create a new squad, save it, then changed the squad's name and saved it again.

### Language

The affected language(s).

**Comment by paulhdunlap** [comment] 2020-01-23 02:03
Having the same problem.

Windows 10
Chrome & Edge

**Comment by Jackpritchard87** [comment] 2020-01-23 10:22
Me too. Only happens in faction once I've built a new squad. If I reload and then delete the newly built squad I can load my old lists.

**Comment by raithos** [comment] 2020-01-24 01:41
duplicate of #514

**Closed by raithos** 2020-01-24 01:41 UTC
