### ISSUE TITLE
Configuration glitch

### ISSUE THREAD

**Issue by Damo1701** [raithos/xwing#795] opened 2021-05-22 08:16 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.

### Expected Behavior

Apply a configuration upgrade to only one TIE/d Defender

### Actual Behavior

Applies the configuration update to multiple ships in the list or deletes them all when I try to delete one.

### Language

English..

**Comment by Patschke** [comment] 2021-05-22 08:26
That's working as intended. The TIE Defender Elite upgrade has the keyword "standardized". This keyword requires you to either have the upgrade equipped on all your TIE/d or on none of them. YASB will kindly enforce that, to prevent you from creating illegal squads. If you want to learn more about a keyword, you can search for it in the Rules section of YASB. 

Duplicate of #794

**Comment by Damo1701** [comment] 2021-05-22 08:33
> That's working as intended. The TIE Defender Elite upgrade has the keyword "standardized". This keyword requires you to either have the upgrade equipped on all your TIE/d or on none of them. YASB will kindly enforce that, to prevent you from creating illegal squads. If you want to learn more about a keyword, you can search for it in the Rules section of YASB.
> 
> Duplicate of #794

Ok, thanks for the heads up.  That'll teach me for trying to list-build before actually getting a hold of things (on a small screen to boot).

SOrry about that!

**Comment by raithos** [comment] 2021-05-23 01:34
I made a new note in the submission so hopefully people still stop asking about this.

**Closed by raithos** 2021-05-23 01:34 UTC
