### ISSUE TITLE
Cad Bane and Durge are "BountyHunters" and cannot equip Tracking Fob Illicit

### ISSUE THREAD

**Issue by Metalbag** [raithos/xwing#1306] opened 2023-06-30 07:31 UTC
**Describe the bug**
Cad Bane and Durge are "BountyHunters" and cannot equip Tracking Fob Illicit

**To Reproduce**
Select CIS Durge or CadBane, 
try to equip Traking FOB
It is not present in the list of "illicits"

**Expected behavior**
Tracking Fob should appear as

**Screenshots**
![image](https://github.com/raithos/xwing/assets/114167599/316935db-9771-4d73-b5ac-cd2e98377776)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Versión 114.0.5735.199 (Build oficial) (64 bits)

**Comment by Patschke** [comment] 2023-06-30 07:35
Duplicate of #1304 and #1300.

I am very sorry that this ruling is so non-obvious (and slightly annoyed that people keep opening new issues without noticing that this already has been reported several times), but: Everything works as intended. The point  pdf apparently decided to change the restriction of the Tracking Fob. Sorry, guess the card is wrong and YASB is right...

**Comment by Metalbag** [comment] 2023-06-30 07:46
Ehhhh, I think you are not right.

[image: image.png]

"Bount Hunter" is a KeyWord (like Dark Side, Droid, Clone, Mandalorian and
so many others


[image: image.png]
CIS and Scum versions of Durge and CadBane have the Bounty Hunter keyword
in the latest point list.

Tracking Fob has never had the restriction of "Scum Only".

Cheers

**Comment by Patschke** [comment] 2023-06-30 07:50
I'm not talking about changes to Durge or Cad Bane. The Tracking Fob has been changed: The [latest point update](https://static1.squarespace.com/static/5ce432b1f9d2be000134d8ae/t/646e49bf182ca91ad7077c00/1684949441475/Upgrade_Points_06.09.23_v2.pdf) did *remove* the "Bounty Hunter" keyword restriction from the Tracking Fob and *add* the "Scum" restriction instead. 

I am well aware how keywords work, but It doesn't matter anymore who is a Bounty Hunter.

**Comment by Metalbag** [comment] 2023-06-30 07:52
Ohhh...

I see now. Thanks for the clarification

**Comment by Metalbag** [comment] 2023-06-30 08:06
Sorry again

[image: image.png]

You were right, but was an error from AMG.

They are really bounty hunters, as  stated in the forum

**Comment by Patschke** [comment] 2023-06-30 08:10
Why do they even have a "restriction" column in the pdf if it is more often wrong than right... So we'll have to decide again if we fix stuff [according to a forum post](https://forums.atomicmassgames.com/topic/11623-tracking-fob-changes/) or if we keep it like this until the actual point document update happens. 

Thanks for pointing this out!

**Comment by Metalbag** [comment] 2023-06-30 08:12
Theoretically,

Whatever is said in the official forum is "official rulling". So, they are
saying that they are going to change the point sheet, because it was a
mistake from their part.

**Comment by raithos** [comment] 2023-06-30 17:09
will be fixed as amg has ruled on the card

**Closed by raithos** 2023-06-30 17:09 UTC
