### ISSUE TITLE
Delta-7b upgrade makes Fancy print preview wrap

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#362] opened 2019-04-19 15:09 UTC
When you add the Delta-7B upgrade to a delta, the resulting "Fancy" printout preview looks like:
![image](https://user-images.githubusercontent.com/10382630/56430144-48e4d800-627a-11e9-9246-0d89cecbc7ba.png)

It printed out fine, though.

**Comment by Patschke** [comment] 2019-04-19 22:09
Yeah, that will also happen for pilots that have too many stats (e.g. Asajj) or too many actions (e..g TIE/sf). As long as everything is fine for the actual print, I did not bother so far. It would of course be possible to make the preview window wider, but I am not sure if that looks much better than having that wrapping header on some ships. Currently I don't think that I want to spend too much time implementing a nice looking multi-line header either, as it is not needed for the actual prints so far. 

If you have any suggestions on how it might be easily possible to have it look nice in the preview as well, those suggestions are of course welcome. As long as I have no real idea how it "should" look like, I am not going to change anything on that ;-)

**Comment by raithos** [comment] 2019-04-30 20:59
Going to close this as right now this is working as intended.

**Closed by raithos** 2019-04-30 20:59 UTC
