### ISSUE TITLE
Ship-Selection doesn't load

### ISSUE THREAD

**Issue by DarkWaaagh** [raithos/xwing#105] opened 2018-09-25 09:17 UTC
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

When I try to build a rebel-squadron for second edition and click to choose a ship, the list should show the choosable ships.

### Actual Behavior

You can't see the List of choosable ships. Theres only "Searching...".

### Language

german

**Comment by Patschke** [comment] 2018-09-25 10:38
Fixed in #106

**Comment by DarkWaaagh** [comment] 2018-09-25 11:28
Same Problem with Francais and Magyar.

**Comment by DarkWaaagh** [comment] 2018-09-25 11:31
Selecting Rebels and English just Shows U-Wing, X-Wing and Y-Wing.

**Comment by Patschke** [comment] 2018-09-25 11:59
> 
> 
> Can't see, that anything has changed.

Well, of course not. It is not live yet.

If you want to see it, you'd need to clone my repo, and build yasb yourself. As soon as raithos visits his repo (which he will usually do once per day), he might merge it and put it live.

**Comment by DarkWaaagh** [comment] 2018-09-25 12:00
Ok, thx.

**Comment by Patschke** [comment] 2018-09-25 12:10
Ah, well. You mentioned two "bugs". 

1.: No pilots showing up when set to german (or any other language but english): will be fixed with #106 
2.: Only showing U-Wing, X-Wing and Y-Wing in "Second Edition" mode: That's not a bug, it's a feature. Standard = all available stuff, including conversion kits, Second Edition = Only expansions available as 2nd edition expansion (which currently is just core set + wave 1)

**Closed** 2018-09-25 17:04 UTC
