### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Noctis85** [raithos/xwing#520] opened 2020-01-23 18:15 UTC
Hello,

I am not able to see any of my Rebel lists however my other lists do show up.  This was broken as of today.

## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by raithos** [comment] 2020-01-24 01:40
duplicate of #514

**Closed by raithos** 2020-01-24 01:40 UTC
