### ISSUE TITLE
Slave 1 expansion in inventory seems to update both YASB 1.0 and 2.0

### ISSUE THREAD

**Issue by InblEric** [raithos/xwing#94] opened 2018-09-21 16:22 UTC
### Expected Behavior

If I edit the inventory in 1.0 or 2.0 it should be independent of the other.

### Actual Behavior

When I add the Slave 1 expansion to my inventory in either YASB 1.0 or 2.0, it also updates my collection in the other app. I have no idea why this could possibly happen but it is happening.

Here's a video of what happens: https://www.youtube.com/watch?v=A8ddN9FNA34&feature=youtu.be

**Comment by iwazaru** [comment] 2018-09-21 18:16
Duplicate of #70?

**Comment by InblEric** [comment] 2018-09-21 20:02
Kind of? But this isn't specific to upgrade cards, this is an entire expansion.

In #70 OP said they added individual upgrade cards to their 1.0 inventory and those cards show up in the 2.0 collection.

In #94 (this one), I added an expansion to my collection and it shows up in both places.

So it's likely the same code causing this but the scope of the bug is bigger than indicated in #70. We could close this and add this info to #70 though if that makes more sense.

**Closed** 2018-09-23 16:48 UTC

**Comment by InblEric** [comment] 2018-09-26 14:26
But I still want to keep track of my 1.0 collection...
