### ISSUE TITLE
Duplicate bombs on reload of list

### ISSUE THREAD

**Issue by theoriginalmoser** [raithos/xwing#266] opened 2019-01-17 03:59 UTC
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.
**Note 3:** If you have a resistance list with the falcon before the missile slot was added, and cant see it when you load it, please re-add your crew slots. This is a known issue when loading old lists into a  ship configuration that has changed, they will load upgrades into slots that dont belong there.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment] 2019-01-17 07:50
That is an duplicate of #264. If you have additional information please add them there. If the title is all the information you got please close this issue. I am going to fix that bug, but it seems not urgent to me - so give me a day or two ;-)

**Closed** 2019-01-17 23:52 UTC
