### ISSUE TITLE
Clone pilot clones the top pilot rather than the one corresponding to the button pressed

### ISSUE THREAD

**Issue by yankeeguy76** [raithos/xwing#462] opened 2019-11-10 17:04 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** When switching between Epic and other formats, the Command upgrades stay on the ships, though no new upgrades are selectable. Please note that in your list building, I am aware and working on a fix for that issue.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment] 2019-11-10 20:28
Could you give a more specific description which ships/pilots are affected? Otherwise I am not able to reproduce this behaviour, and am therefore unable to fix it. I just tested cloning a Y-Wing Gold-Squadron or Y-Wing Gray-Squadron Pilot and both worked as expected. 

Please note that most pilots are unique: If you are trying to clone a unique pilot, the first available pilot from the list will be added instead. This is not a bug, but a feature. Only one unique card with the same name is allowed per squadron.

**Comment by yankeeguy76** [comment] 2019-11-10 21:44
That is a great point that I missed. I was hoping to build an escalation squad with the same upgrades and simply change the pilot, when I chose the "clone pilot" option off of the 2nd pilot (slightly more robust ship build) for my 3rd ship, it cloned my 1st ship instead. I hadn't considered the site limiting it because the individual pilot had already been used.

Thanks

Sent from Outlook on Android.

________________________________

**Comment by raithos** [comment] 2019-11-19 18:17
I'm going to close this, it seems to me everything is working as intended.

**Closed by raithos** 2019-11-19 18:17 UTC
