### ISSUE TITLE
Lost all Scum & Villiany builds

### ISSUE THREAD

**Issue by K25velo** [raithos/xwing#516] opened 2020-01-23 15:26 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chryome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.
Sometime between 10:30 PM and 10:00 AM all of my existing scum builds. In addition I can't save new one. None of the other factions are affected.
### Language

The affected language(s).

**Comment by raithos** [comment] 2020-01-24 01:39
duplicate of #514

**Closed by raithos** 2020-01-24 01:39 UTC
