### ISSUE TITLE
Strange visibility bug

### ISSUE THREAD

**Issue by tinitaet** [raithos/xwing#449] opened 2019-10-19 19:09 UTC
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** I have been told from someone at FFG that the 0-0-0 and BT-1 are actually Hyperspace legal for scum as well. Don't @ me.

### Expected Behavior

Hovering the mouse over a pilot's name should display his stats/abilities on the right.

### Actual Behavior

**Sometimes** this dosen't work with Chertek (Nantex Starfighter). I wasn't able to find the exact conditions, and it seems to be dependend on the time, date, device, the condition of the popes bowels and the weather at a very specific island in the pacific, but when it happens it stays, even if I reload the page or change the language. This **only** happens with Chertek so far...

### Language
all

Have fun with this one...

**Comment by raithos** [comment] 2019-10-29 03:38
I have not been able to reproduce it. We made a bunch of changes recently, can  you confirm you can still pop this bug?

**Comment by raithos** [comment] 2019-11-19 18:20
Closing this since it's been a few weeks and haven't seen a response.

**Closed by raithos** 2019-11-19 18:20 UTC
