### ISSUE TITLE
Stealth Device should not give cloak action

### ISSUE THREAD

**Issue by eblingus** [raithos/xwing#706] opened 2021-01-04 00:35 UTC
Stealth Device gives cloak action, and it should not.

**Comment by Patschke** [comment] 2021-01-05 11:12
It does not do that for me. It is also looking very innocent in the code, so I would be surprised if there is something like a specific combination that triggers this bug. 

Could you provide any additional information on how to encounter this behaviour (e.g. specific ships, combinations of upgrades, browser, ...?). As long as I am unable to reproduce a bug, I cannot investigate or fix it.

**Comment by raithos** [comment] 2021-01-08 06:51
are you using internet explorer/edge?

**Comment by raithos** [comment] 2021-01-17 07:08
I'm going to close this until I get a response, as there is nothing in the code to suggest that this actually happens.

**Closed by raithos** 2021-01-17 07:08 UTC
