### ISSUE TITLE
Can not load Scum Squadrons

### ISSUE THREAD

**Issue by Diemilkweed** [raithos/xwing#1399] opened 2024-06-22 12:48 UTC
**Describe the bug**
Scum squadrons will not load.  All other factions load instantly.  I have tried in chrome and firefox on my personal computer, my work laptop (dell).  Both run windows 10.

**To Reproduce**
Try to load scum squadrons.  The loading circle just keeps circling.

**Expected behavior**
Squads load quickly as they do for all other factions.

**Screenshots**
na

**Desktop (please complete the following information):**
 - Windows 10
 - chrome and firefox
 

**Additional context**

**Comment by raithos** [comment] 2024-06-25 02:10
can you share the URL of the list? sounds like bad url formatting.

**Comment by Patschke** [comment] 2024-07-16 15:05
For me everything works just fine. I guess we can't do much without further information on the issue you have...

**Comment by raithos** [comment] 2024-07-16 15:26
I am closing this until we get a response

**Closed by raithos** 2024-07-16 15:26 UTC

**Comment by Diemilkweed** [comment] 2024-07-17 03:05
I cannot share a url of a list because I cannot get any lists to load.

**Comment by Patschke** [comment] 2024-07-17 06:20
Does that only happen in specific circumstances? E.g. specific pilots that are broken and part of those squads, or specific game modes only or...? If I test this by creating some scum squad, saving it and try to load it everything works just fine. 

Just to make sure we are talking about the same thing: 
 * you are at https://yasb.app (not at e.g. https://yasb.app/old, https://xwing-legacy.com, ...)?
 * you try to load a saved squad from the build in loading/saving (not loading some xws or opening some URLs)?
 * this issue is occurring for recently saved squads, e.g. if you create a new squad and save it, you cannot load it (we are not infinitely long backwards compatible, but usually for a decent time - if you'd try to load some 1.0 squads it would certainly fail)?

A bug that we cannot reproduce will be very hard to fix. So if this happens for some reason for you but not for us, we'll need your help in figuring out the cause of this. Does your browser show any errors (ctrl+shift+k in firefox, ctrl+shift+j in chrome to open the dev tools console)?

**Comment by Diemilkweed** [comment] 2024-07-17 15:00
It happens in firefox and in chrome.  When I am in regular old yasb - the
current 2.5 version - and I hit the "load squads" button.... nothing
happens.  It sits there spinning hte circle at me.  Here's a screen cap

It will not load any squads at all.  WHen I create new ones, and save them,
it will not load those.  No squads, of any sort.
