### ISSUE TITLE
Toggle Previous Points On/Off

### ISSUE THREAD

**Issue by AlexMMejia** [raithos/xwing#1089] opened 2022-05-21 14:53 UTC
## YASB 2.0 Feature Request

So its pretty common to have events between the present and the official rollout of the new points. Would it be possible to add a button to enable the previous version's points?

### Requested Behavior

The ability to toggle between "newest points" and "previous version".

### Actual Behavior

Currently yasb.app only shows the lastest version immediately after it updates.

### Language

The affected language(s).

**Comment by Patschke** [comment] 2022-05-21 15:25
TLDR: yasb.app/old

This feature exists. Duplicate of e.g. issue #1086

Please spend at least a minutes to check if an issue already was reported.

**Closed** 2022-05-21 23:46 UTC

**Comment by AlexMMejia** [comment] 2022-05-23 20:20
First I've ever heard of yasb.app/old maybe thus feature should have a link or button in the corner to avoid future trouble tickets.
