### ISSUE TITLE
Only Red/Purple Actions are printing in Fancy style

### ISSUE THREAD

**Issue by lazyj-bam** [raithos/xwing#650] opened 2020-10-28 18:35 UTC
### Expected Behavior

After building a squad:
1. Click Print / Export list. 
2. In the print options, choose Fancy style. 
3. Click Print. 
4. All colors (Red, Black and Purple) for action icons visible on preview.
5. All colors (Red, Black and Purple) for action icons visible on print.

*believe this worked as of Oct 16, but not 100% sure about that*

Tested on all factions and game types. 

### Actual Behavior
In steps 4 and 5, only the Red and Purple action icons are visible and print. The Black icons appear to have characters in the PDF but do not show up as visible.

Re-attempted in different browsers and even with friends on different computers. 

### Language
English

**Comment by luc-girod** [comment] 2020-10-30 09:34
I think the issue is here, and that the ".action" style isn't used.
https://github.com/raithos/xwing/blob/ea0631faf67009e0560782222eca990889fe1a30/stylesheets/xwing-print.sass#L246

**Comment by Patschke** [comment] 2020-10-30 11:10
I am unable to reproduce this bug (tested with latest bare Chromium and Firefox, on an Arch system) . For me Fenn Rau looks as below, if I create a squad containing just him:

![image](https://user-images.githubusercontent.com/17853362/97697936-05426f80-1aa8-11eb-8412-98af1372eade.png)

Did the squads you used contain any specific combination of upgrades or pilots? Do any errors show up in the log (ctrl+shift+k in firefox, ctrl+shif+j in chrome)?

**Comment by luc-girod** [comment] 2020-10-30 12:02
@Patschke This is how it looks like when you click print, but then, when you actually send this to a printer, the preview (and the print) do not have the black actions.

**Comment by Patschke** [comment] 2020-10-30 12:30
Ah, thanks for the clarification. I was just to dumb to follow the how to reproduce steps. I saw preview, and stopped reading (and probably thinking). I can reproduce this bug an will look into fixing it.

**Comment by Patschke** [comment] 2020-10-30 13:13
Will be fixed with PR #652 
I just set the default color for fonts in prints to black in 
8b1b26f, as white is probably not a good choice for most cases.

**Comment by luc-girod** [comment] 2020-10-30 13:17
Super, thank you!

**Comment by lazyj-bam** [comment] 2020-10-30 19:06
Awesome thanks!

**Closed** 2020-10-30 21:20 UTC
