### ISSUE TITLE
Firefox - poor performance after adding ship and clicking on pilots

### ISSUE THREAD

**Issue by XPav** [raithos/xwing#261] opened 2019-01-11 04:11 UTC
Using Firefox 65.0b9 (64-bit)

So I add a new ship to my squad.  I click the dropdown to pick the pilot and I wait... 3 seconds.

I am logged in.

I don't believe it did this on older Firefox releases

**Comment by raithos** [comment] 2019-01-11 20:43
is this a beta version? its not listed on firefox's official releases.

**Comment by raithos** [comment] 2019-01-13 07:05
have you tried logging into your profile from google chrome or microsoft edge? I'm not seeing the issue on my version of firefox so it could be your account.

**Comment by XPav** [comment] 2019-01-13 21:57
Doesn't do it on Chrome.

Here's a profile from Firefox, it looks to be something in Firefox's guts, but I'm no expert at that.
[slowyasb.zip](https://github.com/raithos/xwing/files/2753576/slowyasb.zip)

**Comment by raithos** [comment] 2019-01-14 22:21
Can you also confirm that you've tried to remove cookies and cache as well?

**Comment by XPav** [comment] 2019-01-15 02:36
I made a new profile, did nothing but log into Google, then log into YASB.

Nice and zippy fast.   So it's something in profile, cache, cookies, or I need to go find the proper chicken to sacrifice. 

Thanks

**Comment by XPav** [comment] 2019-01-30 03:21
I'm going to re-open this, because I can reproduce part of it.

1) Set all individual ships in collection to 0.   
2) Hit drop down, nice and fast.
3) Put my ships back in (2x A-Wing, 2x B-Wing, 1x Aggressor, 4x Z-95)
4) Add new ship, hit drop down.  Slow.

Firefox 65.0 (64-Bit) on Windows.

**Comment by XPav** [comment] 2019-01-30 03:45
Yeah, I've found the root cause:  Firefox's Autofill from Address features.   Ran the Gecko profiler, saw the call tree, then turned off just Autofill, and poof, super fast.

Now, apparently...   https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

It's best to set autocomplete="nope" or something other than off?    I'm now outside of my element. :)

**Comment by zacharyp** [comment] 2019-01-30 10:19
I just tried locally to have all the input boxes have autocomplete="nope", and Firefox was still slow.

I have looked into the Firefox issue a bunch (most notably in September).  I believe that the issue is that yasb is using a very old version of the Select2 library, i.e. version 3.4.0.  I also believe that if we could get to version 4.*, then Firefox would be responsive.

Unfortunately, that upgrade is a bit painful, as their whole paradigm for how the plugin works changed between version 3.* and 4.* 

I may try again at some point, but my time is very limited right now.

**Comment by zacharyp** [comment] 2019-01-30 10:20
Migration path: https://select2.org/upgrading/migrating-from-35

**Comment by raithos** [comment] 2019-01-31 16:18
ok. this is going to be an intense path

**Comment by raithos** [comment] 2019-02-07 03:36
I have not been able to replicate this issue on Firefox version 65.0. I'm not sure whats different between my Firefox and yours

**Comment by XPav** [comment] 2019-02-08 22:59
Do you have "Address Autofill" turned on and a saved address in there?  (The street-address-mail-me-physical things" one.

**Comment by raithos** [comment] 2019-03-08 23:40
So, I'm going to actually close this. I don't think its realistic to do a select2 migration at this time, and while that should be something we look at, it's not going to be triggered from this specific issue. When there are no autofill options the site runs normally, with or without collection. I cannot reproduce the issue with my account (but I don't have any autofilled entires which is the only condition not met). 

If that is in fact the root cause, you can manually remove autofilled options by pressing down on any field (like the ones that show up in the drop downs for adding ships or upgrades), and pressing delete after selecting an option. Or you can add an add-on such as this one https://addons.mozilla.org/af/firefox/addon/form-history-control/ to control which autofilled entires are on YASB specifically (though to be honest, there shouldn't be a need to save any fields for autofill anyway).

**Closed by raithos** 2019-03-08 23:40 UTC

**Comment by XPav** [comment] 2019-03-09 01:17
So in my web browser of choice I have to trade:

- good YASB perfomance vs
- address autofill

Hrmmm.... YASB it is!   :)

**Comment by XPav** [comment] 2020-06-12 23:51
Here's the latest profile that's going slow.

https://share.firefox.dev/2B1BkmX

**Comment by raithos** [comment] 2020-06-13 00:07
can you do me a favor? go to https://yasb-backend.herokuapp.com/headers while logged in and post the contents here.

**Comment by XPav** [comment] 2020-06-13 00:53
'''
{"headers":{"HTTP_ACCEPT_LANGUAGE":"en-US,en;q=0.5"}}
'''

**Comment by raithos** [comment] 2020-06-13 05:34
this was very helpful. can you try loading again? i pushed some loading optimizations

**Comment by XPav** [comment] 2020-06-15 17:06
Works fast now.  I think there's a tiny delay when you hit the first drop down, but its so slight that I could be imagining it (and haven't gone and checked if it does the same thing on other browsers).
