### ISSUE TITLE
Separtists -  Error 2 ships missing abilities

### ISSUE THREAD

**Issue by eagletsi111** [raithos/xwing#348] opened 2019-04-03 12:32 UTC
### Expected Behavior

Under the Vulture Class droids ships.   Both Trade federation Drone and Separatist Drones should have Networked Calculations.   It's on their card, but here it doesn't show.

### Actual Behavior

Both Trade federation Drone and Separatist Drones Do not have Networked Calculations.   It's on their card, but here it doesn't show.

### Language

The affected language(s). 
English

**Comment by Patschke** [comment] 2019-04-03 12:33
Duplicate of #344 and fixed in #347

**Comment by eagletsi111** [comment] 2019-04-03 12:58
No it is not a duplicate.  !!!!      The problem still exists please read this throughly.

**Comment by Patschke** [comment] 2019-04-03 13:04
I've read it again, and am still pretty sure it is a duplicate. The same bug was already reported (see above), and is fixed in the next PR (see above). That PR is simply not live yet. If you can't wait to see the problem beeing fixed, you'll need to compile YASB yourself. If that is no option for you, please wait until the next update goes live (usually within the next three days). This issues did not seem urgent.

**Comment by eagletsi111** [comment] 2019-04-03 13:08
It is a duplicate,  but I didn't know it required 3 days to be fixed.    Sorry.      I'll check back in 3 days.

Thanks,

**Comment by Patschke** [comment] 2019-04-03 13:10
You're welcome. 

It does not require 3 days of work to fix something like that, the 3 minutes work involved have already been done - we just don't publish an update with every single little bug fix. So it will be live as soon as there is enough for the next small update ;-)

**Comment by eagletsi111** [comment] 2019-04-03 13:21
Got it!    Thanks,


    On Wednesday, April 3, 2019, 9:10:54 AM EDT, Patrick Mischke <notifications@github.com> wrote:  
 
 
You're welcome.

It does not require 3 days of work to fix something like that, the 3 minutes work involved have already been done - we just don't publish an update with every single little bug fix. So it will be live as soon as there is enough for the next small update ;-)

**Closed** 2019-04-04 03:30 UTC
