### ISSUE TITLE
Firefox: Slow load times when logged into Google

### ISSUE THREAD

**Issue by markargente** [raithos/xwing#799] opened 2021-05-23 17:35 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior
Firefox: Logged in (Google / Discord)
When selecting pilots/upgrades/etc, I expect it the drop down to appear fairly quickly and respond to clicks. 

If I log out of on Firefox, or use a different browser, it works just fine

### Actual Behavior

If i select a new pilot/ship and then try to select an upgrade to change, it takes roughly 7-8 seconds for it to recover. Adding any additional upgrades after that initial 7-8 seconds is fine on ships that have already been added to the list. Adding a new ship, or changing that ship/pilot will cause it to happen all over again.

This only happens when I log in (to save squads) and only on Firefox browser. I tried with Google and Discord auth, same issue. If i log out, there is no problem. if i do it on the Edge browser, i don't experience any issues.

I've also cleared out all my cookies recently and remains to be the case

### Language

The affected language(s).

**Comment by raithos** [comment] 2021-05-23 17:48
this is a duplicate of the ongoing #707, please look there. Also some people find that disabling auto fill options in settings resolves the issue

**Closed by raithos** 2021-05-23 17:48 UTC
