### ISSUE TITLE
Del Meeko missing modification slot

### ISSUE THREAD

**Issue by CloakerCobra** [raithos/xwing#1303] opened 2023-06-26 21:36 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment] 2023-06-26 22:02
Duplicate of #1301 
Will be fixed with PR #1302

**Closed** 2023-06-30 17:08 UTC
