### ISSUE TITLE
Severe lag on firefox 88.0.1 64-bit (windows)

### ISSUE THREAD

**Issue by lyonheart286** [raithos/xwing#792] opened 2021-05-20 04:06 UTC
### Expected Behavior

I expect the webpage to function normally on firefox the way it does on literally every other browser I have used.

### Actual Behavior

When I click on a drop down menu, the page becomes completely unresponsive for an extended period of time (usually several seconds to a minute, but sometimes more). Nothing on the page can be clicked or selected, but the menu can be scrolled as normal. The page sometimes can't be refreshed either when in this lag. After the lag from opening menu has faded, when anything is selected a similar lag happens, but it generally has a slightly shorter duration. While the lag is happening, everything else on my computer functions normally, including other tabs in the same firefox window. 

### Language

English.

**Comment by raithos** [comment] 2021-05-23 02:17
this sounds like a duplicate of #707 so I'm going to close this for now. Respond if you think this is a different issue and explain how and I'll reopen

**Closed by raithos** 2021-05-23 02:17 UTC
