### ISSUE TITLE
Sensor Buoy equip restrictions inversed

### ISSUE THREAD

**Issue by Netherhigal** [raithos/xwing#685] opened 2020-12-03 07:16 UTC
### Expected Behavior

Sensor Buoy Suite should be usable by Medium and Large Base ships on first order

### Actual Behavior

Lists restriction as Small Base only, First Order, only selectable by said conditions being met

### Language

English

**Comment by Patschke** [comment] 2020-12-03 08:17
Thanks for a note, was caused by a rewrite of our restriction system. Will be fixed.

**Closed** 2020-12-04 21:09 UTC
