### ISSUE TITLE
Auto-includes/useless cards

### ISSUE THREAD

**Issue by smart-architect** [raithos/xwing#550] opened 2020-03-27 01:07 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

Specifically -
When using the 'Random' list builder for Empire, and a gunboat is selected, one of the two zero-cost configurations should always be selected.  

Generally -
When no other upgrade is selected for a slot, if a 0 point upgrade is available, it should be selected/randomly picked from other 0 point upgrades in the slot.  
To my knowledge, this is:
Assault Gunboat configurations (Assault and Arsenal)
Jamming Beam
R5-TK (Scum astromech)
Phantom (Rebel shuttle title, with Ghost)

It should not be possible for the Random list to include crew/gunner/EPT's for ships that cannot use those cards.  
Empire examples;
Alpha Class Starwing - Trajectory Simulator/Delayed Fuses (No Payload slot), Targeting Computer (Already has Lock action), Juke (No Evade action)
Lambda Class - Trajectory Simulator/Delayed Fuses (No Payload slot)
TIE v1 - Trajectory Simulator (No Payload slot), Instinctive Aim (while no munition equipped)
TIE x1 - Trajectory Simulator/Delayed Fuses (No Payload slot), Juke (No Evade action), Targeting Computer (Already has Lock action), Instinctive Aim (while no munition equipped)
TIE Defender - Trajectory Simulator (No Payload slot)
TIE Interceptor - Munitions Failsafe/Delayed Fuses (No Munitions/Payload slot)
TIE Reaper - Squad Leader (Already has red Coordinate), Munitions Failsafe/Delayed Fuses (No Munitions/Payload slot)
TIE Aggressor - Skilled Bombardier/Delayed Fuses (No Payload slot), Targeting Computer (Already has Lock action)
TIE Punisher - Hotshot Gunner/Agile Gunner (No Turret)
TIE L/N - Munitions Failsafe/Delayed Fuses (No Munitions/Payload slot)
TIE Phantom - Trajectory Simulator/Delayed Fuses/Munitions Failsafe/Skilled Bombardier/Hotshot Gunner/Agile Gunner (No Payload/Munition/Turret slot), Targeting Computer (Already has Lock action)
TIE Bomber - Skilled Bombardier/Hotshot Gunner (No Turret slot), Targeting Computer (Already has Lock action), Juke (No Evade action)
TIE Striker - Hotshot Gunner/Agile Gunner/Munitions Failsafe (No Turret/Munitions slot)
Decimator - Juke (No Evade action), Targeting Computer (Already has Lock action)

### Actual Behavior

1 - 
I tested this by hitting Random 30 times and checking the lists.  
Out of the 10 times gunboats appeared, only 2 of them had a 0 point configuration assigned.  
Both cases were Rho Squadron gunboats.  
The rest of the gunboats were Nu Squadron, Rho Squadron, and Karsabi.  

2 -
Ships can frequently include upgrades they cannot use, significantly reducing their effectiveness and the power of this tool.  

I accept this may be a FEATURE, not a bug.  
If this is a problem you want to see fixed, I'm prepared to repeat this exercise for all factions.  Contact me on dunn.christopher.j@gmail.com

It's just that I've picked Empire for the JTO and I got two gunboats without configurations, and one has Juke -

https://raithos.github.io/?f=Galactic%20Empire&d=v8ZsZ200Z163X123W113W135W311W164WY394X74WWY190XW100WW76WY162XWWWWW&sn=Unnamed%20Squadron&obs=

And I feel like this list would have been so much greater if my gunboats had their 0 point configurations.  UGH.  

### Language

The affected language(s). 
English?

**Comment by Patschke** [comment] 2020-03-27 11:46
The first part (fill 0-points) is simple, I've implemented it as part of #551 

![grafik](https://user-images.githubusercontent.com/17853362/77751771-9ccd7480-7026-11ea-9ed8-e648caef1066.png)

It does not require a list of specific 0-point upgrades, but simply fills all empty slots with 0-point upgrades wherever possible after randomization is completed. 

The second part is (in a general form) harder. E.g. Sabine (crew) is useless, as long as you do not have any bombs in your squad - so spotting "useless" cards is not just cards  for specific ships. If we limit usefullness to banning certain cards for certain ships, it would of course be doable. 

So what I worry more about: We'd need to maintain this additional "useless-list", as more ships and upgrades are beeing published. We already had feature requests with people offering their help in crunshing in data (e.g. when implementing the whole quick-build stuff), but they always dissaperared quickly again after the coding was done from our side and data needed to be addeed (e.g. after their faction was done or new stuff was published). This experience lets me hesitate in writing code for that. The list you provided for the empire would need to be converted in a computer-readable format, and of course done for all factions. But you should be aware, that this is not a single-time task, but needs updating with probably every single future release of new cards and ships.

**Comment by raithos** [comment] 2020-03-28 01:57
Since right now there's the whole jank tank tournament, I might not implement this until after all drafting is done. I am going to check in with those guys first before I do anything regarding this

**Comment by raithos** [comment] 2020-03-28 02:08
regarding the second part, this is a feature not a bug. randomizer should only check what is legally allowed on the slot, not whether or not its good or helpful. That's not the job of the randomizer. 
We aren't going to do anything about that.

Also, I'd argue that munitions failsafe shouldn't be in any list.

**Comment by Patschke** [comment] 2020-03-28 08:13
I'd argue, that the missing 0 points is a feature as well. The default behaviour will still be no 0 point filling, so this would of course also be the case for the uselessness avoidance. Having an option to make the randomizer less random seemed ok for me

**Comment by XPav** [comment] 2020-04-02 22:55
FWIW, here's my "completely useless upgrade" checker from my Jank Tank stats collection.   
```
            useless |= (u == 'trajectorysimulator' and bombcount == 0)
            useless |= (u in [ 'andrasta', 'genius', 'delayedfuses', 'cadbane', 'skilledbombardier' ] and devicecount == 0)
            useless |= (u == 'perceptivecopilot' and not 'Focus' in actiontype)
            useless |= (u == 'bazemalbus' and not 'Focus' in actiontype)
            useless |= (u == 'r3astromech' and not 'Lock' in actiontype)
            useless |= (u == 'firecontrolsystem' and not 'Lock' in actiontype)
            useless |= ('ability' in upgrade and 'Attack ([Lock])' in upgrade['ability'] and not 'Lock' in actiontype)
            useless |= ('ability' in upgrade and 'Attack ([Focus])' in upgrade['ability'] and not 'Focus' in actiontype)
            useless |= (u in [ 'gnkgonkdroid', 'inertialdampeners', 'r2d2-crew', 'r2astromech', 'r2d2' ] and shields == 0)
            useless |= (u in [ 'saturationsalvo', 'munitionsfailsafe', 'os1arsenalloadout', 'instinctiveaim' ] and torpsmissiles == 0)

            if u in [ 'hotshotgunner', 'agilegunner', 'bistan', 'hansolo']:
                if not 'Single Turret Arc' in arcs and not 'Double Turret Arc' in arcs:
                    useless = True

            useless |= (u == 'outmaneuver' and not 'Front Arc' in arcs)
            useless |= (u == 'veterantailgunner' and not 'Rear Arc' in arcs)
            useless |= (u == 'agilegunner' and sdata['xws'] == 'tiesffighter' ) 

            if u == 'paigetico':
                if not 'Single Turret Arc' in arcs and not 'Double Turret Arc' in arcs: 
                    useless = True
                if bombcount == 0:
                    useless = True

            useless |= (u == 'jabbathehutt' and illicits == 0)

            useless |= (u =='squadleader' and 'Coordinate' in originalactions )
            useless |= (u =='targetingcomputer' and 'Lock' in originalactions )
            useless |= (u =='havoc' and astromechs == 0 and sensors == 0 )
            useless |= (u =='xg1assaultconfiguration' and cannons == 0 )
```

It does not catch "Squad level" uselessness like:
* Ketsu with no Tractor ability in squad
* Sabine with no bombs in the list 
* Any tactical relay with no calculate in the squad
* IG-2000 with no other Aggressors
* Landos Falcon with no Escape Craft
* Hound's Tooth with no Z-95

And it does not deal with Juke (because that's a little complicated) or Rebel Chopper (because I'm lazy).

**Comment by raithos** [comment] 2020-04-02 23:01
Yeah we're definitely not going to create a per upgrade style condition check, I have no interest in pursuing something like that as bad upgrade choices is inherent to the purpose of randomizer.

**Comment by XPav** [comment] 2020-04-02 23:01
Also, the following upgrades account for 58% of the completely useless ones (in order):

1. Delayed Fuses
2. Munitions Failsafe
3. Trajectory Simulator
4. Targeting Computer

The next add another 18%:
5. Skilled Bombardier
6. Agile Gunner
7. Hotshot Guner

**Comment by XPav** [comment] 2020-04-02 23:08
It's probably an open question why Veteran Turret Gunner has specific arc requirements when Agile Gunner, Hotshot Gunner, Bistan, and Han Solo don't though.

**Comment by Patschke** [comment] 2020-04-03 07:53
> 
> 
> Yeah we're definitely not going to create a per upgrade style condition check, I have no interest in pursuing something like that as bad upgrade choices is inherent to the purpose of randomizer.

I can see a differenc between bad upgrades and useless upgrades. If people want to actually play random lists, and currently run post-processing to do so, I don't see a reason for not adding an option to do that post-processing like discarding of useless upgrades directly in YASB. I totally agree, that this should not be the default behaviour, but I can see it as toggelable option.

**Comment by raithos** [comment] 2020-04-11 08:03
I am going to close this as we have merged the commit that @Patschke made. I don't have any intent to go further than that for this issue

**Closed by raithos** 2020-04-11 08:03 UTC

**Comment by Patschke** [comment] 2020-04-11 09:52
If somebody would want to maintain such a list (in computer-readable form), I'd consider implementing an option to respect that list for randomization. As there was no indication that @smart-architect would be willing to contribute in keeping a uselessness list up to date (and neither did @XPav) I agree that it is nothing we should implement right now.
