### ISSUE TITLE
C-ROC with stalwart captain and broken horn loses crew when loading url

### ISSUE THREAD

**Issue by thomric2** [raithos/xwing#531] opened 2020-02-05 14:35 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

URL loads complete list including all crew slots on C-ROC

Syndicate Smugglers (58)    
    Stalwart Captain (6)    
    Point-Defense Battery (9)    
    Boba Fett (4)    
    Damage Control Team (3)    
    Tibanna Reserves (3)    
    Deadman's Switch (2)    
    Broken Horn (4)    
    0-0-0 (5)    
    Contraband Cybernetics (2)    
    
Ship total: 96  Half Points: 48  Threshold: 8    
    
    
Total: 96    
    
View in Yet Another Squad Builder 2.0: https://raithos.github.io/?f=Scum%20and%20Villainy&d=v8ZeZ500Z376X267W272WW16W277W285WW93W305WW63W92&sn=Unnamed%20Squadron&obs=

### Actual Behavior

As the page loads the crew slots are lost for both 0-0-0 and Boba Fett. Also when the page first loads boba fett is there, but then in a flash boba fett disappears and also Contraband Cybernetics and Deadmans switch swap places.

### Language

The affected language(s). 
English

**Comment by raithos** [comment] 2020-03-04 00:00
FYI i have confirmed this issue, im still looking into a solution

**Comment by Patschke** [comment] 2020-03-27 13:07
Just as a note: The reason is relatively easy to spot: `@unequipOtherUpgrades` is called when Stalwart Captain is added, and the `unequips_upgrades: [ "Crew" ]`in the `cards-common.coffe` of Stalwart Captain will cause all crews to be removed. To avoid this issue, one could simple reorder the slots in  a way that will load the crew after the Stalwart Captain is loaded. 

I did not push a fix, as I am not sure what the reason of `unequips_upgrades` is in the first place. So I'd guess that I break something else if I simply remove it :D If you know what the reason for introducing `unequips_upgrades` was, we could try to find a solution that fixes this issue without breaking whatever it was supposed to achieve.

**Comment by raithos** [comment] 2020-03-28 01:54
unequips_upgrades was first created in 1.0 for crew slots that took up two slots. It would remove the slot if there was an upgrade equipped in the additional slot to ensure it would equip and presumably not create errors.

**Comment by raithos** [comment] 2020-04-17 00:59
This should be fixed now.

**Closed by raithos** 2020-04-17 00:59 UTC
