### ISSUE TITLE
Can't load Imperial lists

### ISSUE THREAD

**Issue by muniaxe** [raithos/xwing#518] opened 2020-01-23 15:43 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you use Microsoft Edge the fonts are messed up. I can't do anything about it, its an issue with the font which is not controlled by me. Also, use Firefox or Chrome instead anyways.
**Note 2:** Some people have noted that their hyperspace lists are completely deleted from the significant changes to the format recently. If you want to resave your old hyperspace lists to extended to preserve them, go to https://raithos.github.io/old for the build with the old points.

### Expected Behavior

I wanted to reload my squads on the imperial site.

### Actual Behavior

When I reload I accidently hit the refresh button and know I can't get my Imperial lists out. I can get all the other factions but I can't get any imperial lists. I've tried to hard refresh, I've tried to clear cookies and also tried to log out and in again.

### Language

English

Its been doing this for 5 minutes now.

![Imperial](https://user-images.githubusercontent.com/60229146/72999201-4ca41d00-3dff-11ea-8685-60e585f8ef68.PNG)

**Comment by raithos** [comment] 2020-01-24 01:40
duplicate of #514

**Closed by raithos** 2020-01-24 01:40 UTC
