### ISSUE TITLE
The langugae selector doesn't work

### ISSUE THREAD

**Issue by Cipo3** [raithos/xwing#107] opened 2018-09-25 11:18 UTC
Only English version works.

## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by iwazaru** [comment] 2018-09-25 11:27
I can reproduce this. Also, I have this error in the console if I choose any language but english:

```
Uncaught TypeError: Cannot set property 'text' of undefined
    at exportObj.setupCardData (xwing.src.coffee:8283)
    at Object.exportObj.cardLoaders.Français (xwing.src.coffee:12652)
    at exportObj.loadCards (xwing.src.coffee:17697)
    at xwing.src.coffee:17717
    at g (xwing.src.coffee:17716)
    at xwing.src.coffee:17715
    at Object.trampoline (xwing.src.coffee:1)
    at a.j [as continuation] (xwing.src.coffee:17715)
    at a._fulfill (xwing.src.coffee:1)
    at xwing.src.coffee:17716
```

**Comment by Patschke** [comment] 2018-09-25 12:00
duplicate of #105

**Closed** 2018-09-25 16:37 UTC
