### ISSUE TITLE
Old 2.0 Version

### ISSUE THREAD

**Issue by Wuselio** [raithos/xwing#1352] opened 2023-12-16 05:54 UTC
**Describe the bug**
I can not sign in to the old 2.0 squad builder

**To Reproduce**
1. Go to 'login'
2. Click on 'discord'
3. Scroll down to 'connect'
4. See error: 404 internal server error 
5. https://[yasb-backend.herokuapp.com/auth/discord/callback?code=rOG1BhyyRfXsNPnlS4jhDMMstKqFUp&state=8096659a8e12ce4c40ae46b1ca16598dede736004c6f9cca](https://yasb-backend.herokuapp.com/auth/discord/callback?code=rOG1BhyyRfXsNPnlS4jhDMMstKqFUp&state=8096659a8e12ce4c40ae46b1ca16598dede736004c6f9cca)

**Expected behavior**
Should log in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser edge
 - Version current

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Patschke** [comment] 2023-12-16 14:52
Duplicate of #1350

**Comment by raithos** [comment] 2023-12-26 05:11
were no longer supporting the old 2.0 builder. we cant fix it due to the original database being removed

**Closed by raithos** 2023-12-26 05:11 UTC
