### ISSUE TITLE
a-wing all getting the vectored-cannon upgrade when adding to one

### ISSUE THREAD

**Issue by nillopillo** [raithos/xwing#838] opened 2021-08-18 18:33 UTC
## YASB 2.0 Bug Report
If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 

**Note 1:** If you can't log in on safari, you may need to set your cookies settings to accept 3rd party cookies.
**Note 2:** Standardized upgrades automatically equip and unequip on all ships AS PER THE RULES. Stop submitting bugs about it please.

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

The affected language(s).

**Comment by Patschke** [comment] 2021-08-19 06:37
The answere to your question is actually in your bug report, since you were too lazy to actually fill it out. Why are so many people unable to read :-( 

Duplicate of #836 and many others before. The behaviour you describe is correct. It is not a bug, but a feature. Standardized upgrades must be equipped on all or no ship of the type. If you wish to build squads that are against the rules, please use the official squad builder. Argh. 

Sorry for the rant, but like half of the latest bug reports are reporting this feature as a bug... Don't get me wrong, it's still welcome to report bugs if you encounter them.

**Comment by nillopillo** [comment] 2021-08-19 06:52
Hi,
I'm very sorry - you are quite right. I will do better in the future :) 
Have a nice day, and keep up the good work.
//Nillopillo

**Closed** 2021-08-20 06:35 UTC
