### ISSUE TITLE
When attempting to load a list from a link, the site just 'spins' loading.

### ISSUE THREAD

**Issue by Chaotix** [raithos/xwing#322] opened 2019-03-06 17:56 UTC
### Expected Behavior

List loads after clicking a link

### Actual Behavior

Site will continue attempting to load the list, but the loading graphic just 'spins' at the top of the screen

### Language

English (all?)

**Comment by raithos** [comment] 2019-03-06 23:07
Can you provide the link here?

**Comment by Chaotix** [comment] 2019-03-07 07:39
https://raithos.github.io/?f=Galactic%20Empire&d=v6!s&sn=Unnamed%20Squadron&obs=&fbclid=IwAR1Goblh0B8-0i0QDMX3VRQKv2_KgmUX2QV7uJzv-xGXKRsXZpmZjSfASMA

**Comment by Patschke** [comment] 2019-03-07 08:26
Where is that Link from? It doesn't look very valid at all, so I am not surprised it does not load. 

We could however implement something to inform users that the link they followed is invalid, rather then displaying a forever spinning icon.

**Comment by Patschke** [comment] 2019-03-07 10:22
Basically our links are easy to read. Your link is containing the following information: 
f=Galactic Empire: It is linking an Imperial squad
d=v6: It is using the most recent version of describing the squad
s=... Missing: There should be something like s=points!Pilot:upgrade... telling how many points were selected as maximum, and which pilots and upgrades are part of the squad (some numbers)
sn=Unnamed Squadron: The squad name
obs=: No Obstacles selected
fbclid=...: Some gibberish inserted by facebook, to help facebook track your activities. We don't use that stuff at all, but facebook will add it to links you click within facebook. 

So all I can tell is, that this link is not valid - the question would be, how it was created - so we can try to fix that.

**Comment by raithos** [comment] 2019-03-08 23:07
not specific to this issue, but I have pushed a change that should shorten urls, somewhat, this will also potentially help facebook links in the future be easier to view

**Comment by Chaotix** [comment] 2019-03-09 01:40
Yes I believe this was a Facebook messenger issue.  I have players emailing
ne links now and that seems to work.  I haven't tried it yet with the
shortened url update.

**Comment by Patschke** [comment] 2019-03-09 19:37
All I can do right now is adding a error message if the url is invalid, as part of #324. As the Issue is not the loading, but rather the creating of that url (loading a squad that is not provided is obviously not going to work), we'd need further information on how that url was created. Otherwise we cannot do much more on this I believe...

**Comment by raithos** [comment] 2019-03-12 21:58
just as a note about the facebook links, it seems to only affect the actual url if it generates a preview image. if you click the preview image it shows the correct linkage. NO IDEA WHATS going on there but I'm going to close this for now as this may get fixed later on as I am looking at ways to shorten links anyways

**Closed by raithos** 2019-03-12 21:58 UTC
