### ISSUE TITLE
Loading squads for faction is broken after recent squad save to that faction

### ISSUE THREAD

**Issue by michaelrstewart1** [raithos/xwing#522] opened 2020-01-23 21:50 UTC
## YASB 2.0 Bug Report
Recently saved squads are causing the faction's load squads action to not return the JSON data in the "additional_data" key. The result is null in the API response, and this causes a javascript error:

Cannot read property 'points' of null

The effect is that when loading a faction's squad list for loading, if that faction has had a squad recently saved, none of the squads for that faction load and the "Fetching squads" spinner persists indefinitely.

### Expected Behavior

After saving a squad, the "Load squad" action should pull up a list of all squads for that faction.

### Actual Behavior

When attempting to load squad selection list for a faction that has had a squad saved recently, the list does not load and the console error shows:

Cannot read property 'points' of null

The JSON data in the REST response also shows that the "additional_data" key for all new squads are null, and this is likely what is causing the error when the faction's squad list is loading.

### Language

English

**Comment by raithos** [comment] 2020-01-24 01:40
duplicate of #514

**Closed by raithos** 2020-01-24 01:40 UTC
