### ISSUE TITLE
randomise squad is including cards I don’t have 

### ISSUE THREAD

**Issue by Widzy5** [raithos/xwing#477] opened 2019-11-28 02:01 UTC
### Expected Behavior

With the option ticked to only include cards in my collection, randomly generated squads should not include any cards I don’t have.

### Actual Behavior

My randomly generated squad always acts like I don’t have the ‘only my cards’ option ticked - ie it’s always a random squad from lol possible cards.

NoteI am a new user - I created a new account, and added my collection (1 core set, 1 t-65 expansion, 1 extra t-65 ship, 1 b-wing expansion, 2 tie/ln expansions, 2 extra tie/on ships, tie advanced x1 expansion, 1 tie defender ship, 5 hull upgrades, 5 shield upgrades).

It then correctly lists all the cards i should have in my collection.  But when I click generate random squad with the ‘my cards only’ option, I still just get a random of all cards

### Language

English.

**Comment by Widzy5** [comment] 2019-11-28 02:04
Ah figured it out - so it only starts working if I refresh the page.  So the bug actually is that the random squads button isn’t taking into account changes made to my collection until the page refreshes

**Comment by Patschke** [comment] 2019-12-06 18:13
Thanks for reporting this bug. I believe you and expect it to be reproduceable by adding new accounts, but am however not going to fix it anyway - simply because the work invested in creating a new Facebook/Google/Twitter Account for each test seems not reasonable to me.

**Comment by raithos** [comment] 2019-12-31 00:37
I'm going to close this as something we aren't going to resolve, since its edge-case is limited to 1 time.

**Closed by raithos** 2019-12-31 00:37 UTC
Labels: wontfix
