### ISSUE TITLE
Adding Maul cree not adding Dark Side Upgrades dropdown 

### ISSUE THREAD

**Issue by Nick-Hansen** [raithos/xwing#120] opened 2018-09-28 14:47 UTC
## YASB 2.0 Bug Report

**Note:** If your page doesn't load, try a hard refresh first. I update at random hours of the day and you may have been accessing the page at one of those times. 
**Note 2:** Some players are finding their 1.0 collections transfer over when the name of the collection item matches with a 1.0 counterpart. This is a known issue. Please update your collections in 2.0 accordingly.

### Expected Behavior

Given I am editing a scum list
And I add a YT-1300
When I add the Maul Crew Upgrade
Then a Dark Side Upgrade dropdown will be added to the YT-1300

### Actual Behavior

Given I am editing a scum list
And I add a YT-1300
When I add the Maul Crew Upgrade
Then no Dark Side Upgrade dropdown is added to the YT-1300

### Language

English

**Comment by iwazaru** [comment] 2018-09-28 14:49
Duplicate of #86?

**Comment by Nick-Hansen** [comment] 2018-09-28 14:57
Yes, this is a duplicate.

**Closed** 2018-09-28 19:06 UTC
