### ISSUE TITLE
Quality of some logos

### ISSUE THREAD

**Issue by luc-girod** [raithos/xwing#430] opened 2019-09-13 08:13 UTC
## YASB 2.0 Bug Report

Hei!
More of a comment than a bug, but when printing a list, a number of logos (focus action, shield logo) are very crisp, but some (red actions, Atk/Def/Hull/Shield/Force values...) are pixelated/compressed. I didn't find where in the code these things were, but it would be nice to homologise the appearance of these logos ;)

**Comment by Patschke** [comment] 2019-09-13 21:13
I am unable to reproduce the behavior you described, so I probably need some more information:

All the icons you mentioned are simply part of the [X-Wing Miniatures Font](https://geordanr.github.io/xwing-miniatures-font/) from geordanr. What print settings and browser do you use? Could you try to print a list as pdf file, and check whether they are crisp in there? 

Afaik the appearance should be as homogeneously as possible. Maybe I am not aware of some differences one may encounter with other settings than mine.

**Comment by raithos** [comment] 2019-09-16 16:36
could you screenshot this for me so I can see specifically what it looks like? I'm leaning towards a local configuration issue but I want to know what I'm looking at since I cant reproduce it either

**Comment by luc-girod** [comment] 2019-09-16 19:03
Hei, 
See here, especially on the Punisher for the red actions :
https://drive.google.com/file/d/1gMpKoZlwb72ePmOx0GjFCGi4Ul50qXv2/view?usp=drivesdk

**Comment by Patschke** [comment] 2019-09-30 07:39
Even if I create the same list, everything works just fine. I have no Issues with the red Punisher actions at all. As long as we can not reproduce the behaviour you describe, we can't fix it - as it is impossible to find the cause. So additional information on your browser, system, print settings, ... might be helpful. 

The pdf you provided renders a blurred barrel roll for me, too. I noticed that it has also weired borders (usually there should be a gap at the top of the second page) and some unusual artifacts on the right end of every header line. So there might be some specific configuartion of your print settings causing those issues. 

However, I will not try to use random uncommon settings hoping to match yours at some point ;-)

**Comment by luc-girod** [comment] 2019-10-09 11:55
Hei,
It seems that it is the "Adobe PDF" virtual printer that fucks it up, the Chrome "Save as PDF" gives super sharp results...

**Comment by raithos** [comment] 2019-10-29 03:36
I was about to close this but I need to make some more adjustments to coloring things in black and white. I unfortunately cant control adobe pdf virual printer.

**Comment by raithos** [comment] 2019-11-19 18:19
I'm going to close this for now, since the specific issue is solved. However, I am still working on general improvements to the printing layouts

**Closed by raithos** 2019-11-19 18:19 UTC
